server:
  port: 8672

spring:
  application:
    name: notehub-message
  data:
    mongodb:
      host: 120.77.176.55
      port: 27017
      database: notehub
logging:
  level:
    org.springframework.data.mongodb.core: DEBUG